use crate::quote::get_quote;
use cp_amm::state::Pool;

#[test]
fn test_quote_jupiter() {
    let base64_string = "8ZptBBGxbbyAlpgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAUAAAAAAABAAAAAAAAAGCk3AC8AwAAAQAKAHgAiBPENohoAAAAAMsQx7q4jQYAAAAAAAAAAAAerN5NA/PSAQAAAAAAAAAAAAk9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIZAv7EUbpx/jlTpQ/LshmC2vZjZMBrwTcOKmjRLyftjG+nrzvtutOj1l82qryXQxsbvkwtL24OR8pgIDRS9dYb2Q+NLTQXBOHZdxZbjqqk+QoyJpGqz6AwA+FXH9OL8ZdEibuFrLOdamFrxRnwK8t06Q65+dcfU3+XctPnnulW0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANpjaB9yhrzIBnGeLCtQogFXJDv8lmixFSC8U4Q+3NsISHp+M4sycRzlBf/c7QEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOCrstsAAAAAAAAAAAAAAAAAAAAAAAAAAFA7AQABAAAAAAAAAAAAAACbV2lOqRpchLHE/v8AAAAAsfR09HnEyQEAAAAAAAAAAP4ghmgAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE28v/MiYPUBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB89TrHAwAAAAAAAAAAAAAAAAAAAAAAAADgq7LbAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAA2mNoH3KGvMgGcZ4sK1CiAVckO/yWaLEVILxThD7c2wgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    let data_bytes = base64::decode(base64_string).unwrap();
    let mut data_without_discriminator = data_bytes[8..].to_vec();
    let &pool: &Pool = bytemuck::from_bytes(&mut data_without_discriminator);

    println!("{:?}", pool);

    let current_timestamp: u64 = 1_753_751_761;
    let current_slot: u64 = 356424202;
    let a_to_b: bool = false;
    let has_referral: bool = false;
    let actual_amount_in = 2000_000_000;

    let swap_result = get_quote(
        &pool,
        current_timestamp,
        current_slot,
        actual_amount_in,
        a_to_b,
        has_referral,
    )
    .unwrap();

    println!("swap_result {} {:?}", actual_amount_in, swap_result);
}
